import type { BotStrategy } from './types';

export const DEFAULT_BOT_STRATEGIES: BotStrategy[] = [
  {
    id: 'conservative-mm',
    name: '稳健做市',
    description: '仓位小，滑点限制更紧，适合先小资金观察。',
    strategyId: 'mm-spread-v1',
    strategyVersion: '1.0.0',
    maxNotional: 10000,
    maxPosition: 0.2,
    maxDailyLoss: 300,
    maxSlippageBps: 18,
    orderRateLimitPerMin: 20,
    quoteSpreadBps: 18,
    orderLevels: 2,
    levelSpacingBps: 12,
    refreshIntervalSec: 8,
    minOrderSize: 0.01,
    maxOrderSize: 0.08,
    inventorySkewBps: 8,
    targetInventoryPct: 50,
    cancelStaleAfterSec: 20,
    postOnly: true,
    heartbeatTimeoutSec: 30,
    maxConsecutiveErrors: 3,
    maxLatencyMs: 1200,
  },
  {
    id: 'balanced-mm',
    name: '均衡做市',
    description: '默认配置，适合常规运行和多账号复制。',
    strategyId: 'mm-spread-v1',
    strategyVersion: '1.0.0',
    maxNotional: 30000,
    maxPosition: 0.6,
    maxDailyLoss: 800,
    maxSlippageBps: 25,
    orderRateLimitPerMin: 35,
    quoteSpreadBps: 14,
    orderLevels: 3,
    levelSpacingBps: 10,
    refreshIntervalSec: 5,
    minOrderSize: 0.02,
    maxOrderSize: 0.18,
    inventorySkewBps: 12,
    targetInventoryPct: 50,
    cancelStaleAfterSec: 15,
    postOnly: true,
    heartbeatTimeoutSec: 25,
    maxConsecutiveErrors: 4,
    maxLatencyMs: 1500,
  },
  {
    id: 'active-mm',
    name: '积极做市',
    description: '下单更频繁，限制更宽，适合确认策略稳定后使用。',
    strategyId: 'mm-spread-v1',
    strategyVersion: '1.0.0',
    maxNotional: 60000,
    maxPosition: 1.2,
    maxDailyLoss: 1500,
    maxSlippageBps: 35,
    orderRateLimitPerMin: 60,
    quoteSpreadBps: 10,
    orderLevels: 4,
    levelSpacingBps: 8,
    refreshIntervalSec: 3,
    minOrderSize: 0.03,
    maxOrderSize: 0.35,
    inventorySkewBps: 18,
    targetInventoryPct: 50,
    cancelStaleAfterSec: 10,
    postOnly: true,
    heartbeatTimeoutSec: 20,
    maxConsecutiveErrors: 5,
    maxLatencyMs: 2000,
  },
];

export const getStrategyPatch = (strategy: BotStrategy) => ({
  strategyId: strategy.strategyId,
  strategyVersion: strategy.strategyVersion,
  maxNotional: strategy.maxNotional,
  maxPosition: strategy.maxPosition,
  maxDailyLoss: strategy.maxDailyLoss,
  maxSlippageBps: strategy.maxSlippageBps,
  orderRateLimitPerMin: strategy.orderRateLimitPerMin,
  quoteSpreadBps: strategy.quoteSpreadBps,
  orderLevels: strategy.orderLevels,
  levelSpacingBps: strategy.levelSpacingBps,
  refreshIntervalSec: strategy.refreshIntervalSec,
  minOrderSize: strategy.minOrderSize,
  maxOrderSize: strategy.maxOrderSize,
  inventorySkewBps: strategy.inventorySkewBps,
  targetInventoryPct: strategy.targetInventoryPct,
  cancelStaleAfterSec: strategy.cancelStaleAfterSec,
  postOnly: strategy.postOnly,
  heartbeatTimeoutSec: strategy.heartbeatTimeoutSec,
  maxConsecutiveErrors: strategy.maxConsecutiveErrors,
  maxLatencyMs: strategy.maxLatencyMs,
});
